#!/bin/bash

COMMAND=$1

#set the correct dir to excute folder
DIR="/home/mi6/Documents/GITHUB/"

#start samza
start_samza(){
    echo "Starting Samza"
    #if already started stop for clear start
    sudo $DIR/hello-samza/bin/grid stop all

    sudo $DIR/hello-samza/bin/grid start all

    #now run the job
  
}

#stop samza
stop_samza(){
    echo "Stopping Samza"
    sudo $DIR/hello-samza/bin/grid stop all

}

#start storm
start_storm(){
    echo "Stating Storm"
    sudo $DIR/storm/zookeeper-3.4.10/bin/zkServer.sh start 
    sudo $DIR/storm/apache-storm-0.9.5/bin/storm nimbus
    sudo $DIR/storm/apache-storm-0.9.5/bin/storm supervisor

    #now start the job
}

#stop storm
stop_storm(){
    echo "Stopping Storm"

    #stop storm888

    #stop zookeeper
    sudo $DIR/storm/zookeeper-3.4.10/bin/zkServer.sh stop
}


# Check arguments
if [ "$COMMAND" == "start_samza" ]; then
  start_samza
  exit 0
elif [ "$COMMAND" == "stop_samza" ]; then
  stop_samza
  exit 0
if [ "$COMMAND" == "start_storm" ]; then
  start_storm
  exit 0
elif [ "$COMMAND" == "stop_strom" ]; then
  stop_storm
  exit 0
else
  echo "Enter commands"
  exit 0
fi